previewsEnabled: false
services:
  - type: web
    name: eustdd-schedule
    env: node
    plan: free
    region: oregon
    branch: main
    rootDir: v1
    buildCommand: npm ci --legacy-peer-deps && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: eustdd-db
          property: connectionString
      - key: DIRECT_DATABASE_URL
        fromDatabase:
          name: eustdd-db
          property: connectionString
      - key: NPM_CONFIG_PRODUCTION
        value: false

databases:
  - name: eustdd-db
    plan: free
    region: oregon
