previewsEnabled: false
services:
  - type: web
    name: eustdd-schedule
    env: node
    plan: free
    region: oregon
    branch: main
    rootDir: v1
    buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: eustdd-db
          property: connectionString
      - key: DIRECT_DATABASE_URL
        fromDatabase:
          name: eustdd-db
          property: connectionString

databases:
  - name: eustdd-db
    plan: free
    region: oregon